    sources:
      - Gluten.glyphs
    axisOrder:
      - wght
      - slnt
    outputDir: "../fonts"
    familyName: Gluten
    stat:
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Book
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
      - name: Slant
        tag: slnt
        values:
        - name: Upright
          value: 0
          linkedValue: -13
          flags: 2
        - name: Oblique
          rangeMinValue: -13
          nominalValue: -13
          rangeMaxValue: -1
        - name: Backslanted
          rangeMinValue: 1
          nominalValue: 13
          rangeMaxValue: 13